// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUdcFrB2O3LKcGCriLz2zxfiI-7K_q9pY',
    appId: '1:164267630176:web:f29a85282bb1a0f4062d05',
    messagingSenderId: '164267630176',
    projectId: 'smarteats-765ae',
    authDomain: 'smarteats-765ae.firebaseapp.com',
    storageBucket: 'smarteats-765ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewdEJB9lU7yueEh23tTSreTwXKYLb0_Q',
    appId: '1:164267630176:android:867be63df9673cc5062d05',
    messagingSenderId: '164267630176',
    projectId: 'smarteats-765ae',
    storageBucket: 'smarteats-765ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeeK4BETCAuHuWAZV4rS2QLwb5v2ujCAY',
    appId: '1:164267630176:ios:5010deda8e720fcd062d05',
    messagingSenderId: '164267630176',
    projectId: 'smarteats-765ae',
    storageBucket: 'smarteats-765ae.firebasestorage.app',
    iosBundleId: 'com.example.smartEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeeK4BETCAuHuWAZV4rS2QLwb5v2ujCAY',
    appId: '1:164267630176:ios:5010deda8e720fcd062d05',
    messagingSenderId: '164267630176',
    projectId: 'smarteats-765ae',
    storageBucket: 'smarteats-765ae.firebasestorage.app',
    iosBundleId: 'com.example.smartEats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUdcFrB2O3LKcGCriLz2zxfiI-7K_q9pY',
    appId: '1:164267630176:web:8761209bb8c34fff062d05',
    messagingSenderId: '164267630176',
    projectId: 'smarteats-765ae',
    authDomain: 'smarteats-765ae.firebaseapp.com',
    storageBucket: 'smarteats-765ae.firebasestorage.app',
  );
}
