import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // IMPORT 1
import 'firebase_options.dart'; // IMPORT 2 (This file was generated by the CLI)
import 'screens/main_screen.dart';

void main() async { // ADD ASYNC
  // 1. Ensure Flutter is ready
  WidgetsFlutterBinding.ensureInitialized();
  
  // 2. Start Firebase using the options we just configured
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SmartEats',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
        useMaterial3: true,
      ),
      home: const MainScreen(),
    );
  }
}